version: "3"

networks:
  dbs-net:
    driver: bridge

services:

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    env_file: 
      - ./db/configs/postgres.env
    ports: 
      - 80:8000
    networks:
      - dbs-net

  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    command: npm start
    ports: 
      - 81:3000
    networks:
      - dbs-net

  db:
    image: postgres:alpine
    container_name: "postgresdb"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - dbs-net
    env_file: 
      - ./db/configs/postgres.env


  # added for easy config
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    env_file: 
      - ./db/configs/postgres.env
      - ./db/configs/pgadmin.env
    volumes:
      - ./data/postgresadmin:/root/.pgadmin
    ports:
      - 5050:80
    networks:
      - dbs-net
  

