version: "3"

networks:
  dbs-net:
    driver: bridge

services:

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports: 
      - 80:80
    networks:
      - dbs-net

  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - 81:80
    networks:
      - dbs-net

  db:
    image: postgres:alpine
    volumes:
      - ./data/policy:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - dbs-net

